fix: add methodresponse into methodOption

diff --git a/api_test/buildspec.yaml b/api_test/buildspec.yaml
--- a/api_test/buildspec.yaml
+++ b/api_test/buildspec.yaml
@@ -4,16 +4,20 @@ env:
   variables:
     REPOSITORY_URL: "https://github.com/aws-samples/Intelli-Agent.git"
     CODE_BRANCH: "dev"
+    PROJECT_NAME: "Chatbot Portal with Agent"
     STACK_NAME: "intelli-agent"
     DEPLOY_STACK: "cdk"
     CLEAN_RESOURCES: "no"
     TEST_FAST: "false"
-    SNS_REGION: "ap-northeast-1"
+    REGION: "ap-northeast-1"
+    EXEC_ROLE: "arn:aws:iam::544919262599:role/agent-api-test-role"
     S3_MODEL_ASSETS_BUCKET: "intelli-agent-rag-ap-northeast-1"
     API_TEST_RESULT_BUCKET: "intelli-agent-rag-ap-northeast-1-api-test"
-    ETL_IMAGE_NAME: "intelli-agent-etl"
+    ETL_REPOSITORY_NAME: "intelli-agent-etl"
     ETL_IMAGE_TAG: "latest"
     SUB_EMAIL: "cuihubin@amazon.com"
+    TOPIC: "arn:aws:sns:ap-northeast-1:544919262599:agent-developers"
+    GEN_REPORT_FUNCTION: "agent-api-test-report-function"
 phases:
   install:
     commands:
@@ -22,18 +26,17 @@ phases:
         echo "----------------------------------------------------------------"
         echo "$install_start_time install start..."
         echo "----------------------------------------------------------------" 
-        aws cloudformation delete-stack --stack-name "$STACK_NAME"
-        aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
         git clone $REPOSITORY_URL --branch $CODE_BRANCH --single-branch
+        echo "build portal assets >>>"
+        pushd Intelli-Agent/source/portal
+        npm i -g pnpm
+        pnpm i
+        npm run build
+        popd
         deploy_start_time=$(date +"%Y-%m-%d_%H-%M-%S")
         echo "----------------------------------------------------------------"
         echo "$deploy_start_time deploy start..."
         echo "----------------------------------------------------------------"
-        npm i -g pnpm
-        pushd Intelli-Agent/source/portal
-        pnpm i
-        npm run build
-        popd
         if [ "$DEPLOY_STACK" = "cdk" ]; then
           if [ -d "Intelli-Agent/source/infrastructure" ]; then
             echo "===================="
@@ -41,9 +44,17 @@ phases:
             pnpm i
             npx cdk deploy --parameters SubEmail=$SUB_EMAIL \
                   --parameters S3ModelAssets="$S3_MODEL_ASSETS_BUCKET" \
-                  --parameters EtlImageName="$ETL_IMAGE_NAME" \
+                  --parameters EtlImageName="$ETL_REPOSITORY_NAME" \
                   --parameters ETLTag="$ETL_IMAGE_TAG" \
-                  --require-approval never || exit 1
+                  --require-approval never
+            deploy_exit_code=$?
+            if [ $deploy_exit_code -ne 0 ]; then
+              echo "CDK deployment failed. Sending email and exiting with status code 1."
+              msg=$(aws cloudformation describe-stack-events --stack-name intelli-agent --query "StackEvents[?ResourceStatus=='CREATE_FAILED'] | [-1]")
+              echo "{\"project_name\":\"$PROJECT_NAME\",\"build_url\":\"$CODEBUILD_BUILD_URL\",\"status\":\"unCompleted\",\"detail\":\"$msg\",\"topic\":\"$TOPIC\"}" > payload.json
+              aws lambda invoke --function-name $GEN_REPORT_FUNCTION --payload fileb://payload.json response.json
+              exit 1
+            fi
             popd
           else
             echo "Directory Intelli-Agent/source/infrastructure does not exist."
@@ -107,9 +118,10 @@ phases:
         aws s3 cp $original_filename "${API_TEST_RESULT_BUCKET}/${report_datetime}_${original_filename}"
         aws s3 cp $original_json_filename "${API_TEST_RESULT_BUCKET}/${report_datetime}_${original_json_filename}"
         aws s3 cp $original_log "${API_TEST_RESULT_BUCKET}/${report_datetime}_${original_log}"
-        echo "{\"project_name\":\"$project_name\",\"build_url\":\"$CODEBUILD_BUILD_URL\",\"s3_key\":\"$s3_key\",\"log\":\"$log\"}" > payload.json
-        aws lambda invoke --function-name gen-api-test-report-lambda --payload fileb://payload.json response.json
+        echo "{\"project_name\":\"$PROJECT_NAME\",\"build_url\":\"$CODEBUILD_BUILD_URL\",\"status\":\"completed\",\"s3_key\":\"$s3_key\",\"log\":\"$log\",\"topic\":\"$TOPIC\"}" > payload.json
+        aws lambda invoke --function-name $GEN_REPORT_FUNCTION --payload fileb://payload.json response.json
       - aws cloudformation delete-stack --stack-name "$STACK_NAME"
+      - aws cloudformation wait stack-delete-complete --stack-name "$STACK_NAME"
       - |
         post_build_end_time=$(date +"%Y-%m-%d_%H-%M-%S")
         echo "----------------------------------------------------------------"
